### ISSUE TITLE
Need for peoper Documentation

### ISSUE THREAD

**Issue by deveshio** [Hirenachhaada/Mern-Chat-Application#1]
I'd like to suggest providing proper documentation for the project
like having a Readme file and a contribution file to 
explain the project and guide contributors

**Comment by Devesh-Daku** [comment]
i'd like to solve the issue

**Comment by Hirenachhaada** [comment]
I was busy with some work. Will provide it shortly. By the way, someone can also take it as the issue and make a well documentation.

**Comment by Hirenachhaada** [comment]
The documentation is added. You can start working on different issues
