### ISSUE TITLE
Forgot Password 

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#15]
If the user forgets his password by sending email to his id he can change his password

**Comment by Surajit0573** [comment]
I can do it, please assign me !!

**Comment by Hirenachhaada** [comment]
ok you can work on it.

**Comment by NandishM0618** [comment]
@Hirenachhaada please assign me this issue I would like to work on this.

**Comment by Hirenachhaada** [comment]
you can start working on it

**Comment by NandishM0618** [comment]
![issue1](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/ea62e802-d947-4f75-9732-d1701f8654dd)
![issue2](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/4166b176-c837-4ee1-a1ba-6baa085b067d)
![issue3](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/f11766fe-69fb-42bc-8d5d-a3cd020d4ec2)
![issue4](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/c77fc5be-f965-4329-a944-140c2d355e30)
I have implemented the forgot password functionality. if you want changes in the above photos please update. PS : I have also included show and hide functionalities for reset password. can I make pull request.

**Comment by Hirenachhaada** [comment]
Nice work, Just adds the app name in Reset password page similar to the login page.

**Comment by NandishM0618** [comment]
?

**Comment by NandishM0618** [comment]
![issue5](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/24ad639d-b95e-4188-acf9-5b64ee98a8a9)
like this ?

**Comment by Hirenachhaada** [comment]
yes, Correct.
Create a PR

**Comment by NandishM0618** [comment]
@Hirenachhaada I have made pull request please review it #33 if any changes required please update me.
