### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#16]
The user should be able to change his password. It should first ask for it's old password. After checking the old password change to password to new password.

**Comment by NandishM0618** [comment]
@Hirenachhaada  please assign this issue to me I would like to work on it.

**Comment by Hirenachhaada** [comment]
done

**Comment by Hirenachhaada** [comment]
you can start working on it. Read the readme file for starting the project in your system.

**Comment by NandishM0618** [comment]
![issue15](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/ea6fadb0-e7a8-468c-874f-bbc171ca582e)
I have implemented update password or change password.

**Comment by NandishM0618** [comment]
![issue18](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/aee7cbe9-6ba0-4268-8365-ce8fdea98a7a)
![issue19](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/f78261a6-598b-489f-9f94-4d32ea7b8a57)
![issue20](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/a9987808-be5f-4094-b6d6-bda2797e1803)
I have implemented change password. if you need changes in design please update me.

**Comment by Hirenachhaada** [comment]
Nice. Also, add a confirm new password input box. And then you can create a pull request. Nice work.

**Comment by NandishM0618** [comment]
Okay

**Comment by NandishM0618** [comment]
![issue21](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/57c7a3fe-a386-450b-b411-df80ac4a501a)
if confirm password does not match it will show error like this.

**Comment by Hirenachhaada** [comment]
ok nicely done. But there is a big mistake. It should not be in the profile section. When you click on someone else profile pic/ view profile button, it will allow you to change other's password also, which is not possible. So just Create a new option in the dropdown for change password.
Also add option to show and hide password.

**Comment by NandishM0618** [comment]
Okay

**Comment by NandishM0618** [comment]
![issue22](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/fc901f19-72f1-4424-b3e3-99ba14fd4ed0)
![issue23](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/100901899/2eabce92-5d8e-4687-875e-9f28d5f0e13f)
I have made changes please review it #19 if any changes required please update me.
