### ISSUE TITLE
Search user while typing it's name/email

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#26]
The user has to click on the Go button to search the user. Try to improve it, which means while typing, the user can see the matched users accordingly. 

While forming the group, users are searched and shown while typing, so if needed, you can get help from it.
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/95188259/4356ba39-bc5e-45f1-92e1-b987260accd7)

**Comment by maheshwar-verma** [comment]
this looks good for me, can you assign me this,

**Comment by maheshwar-verma** [comment]
i have created a pr check that
