### ISSUE TITLE
Align the dropdown for Copy and Delete Message appropriately 

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#3]
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/95188259/0c76440c-aba0-49b0-aaf4-07c705476136)
On hovering a particular message it provides a drop-down for copy and delete message. The alignment is not proper.  Improve it.

**Comment by involk-secure-1609** [comment]
can i be assigned this issue

**Comment by SimonShangpliang** [comment]
can i be assigned this issue

**Comment by Hirenachhaada** [comment]
@SimonShangpliang  you can work on it

**Comment by SimonShangpliang** [comment]
![dark mode](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/118509034/a1c7b8bd-4ed7-40dc-9474-94fb65742f33)
![light mode](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/118509034/68c230c2-003e-4841-b5c9-90476ba839fe)

is this fine or do you want another color for something?

**Comment by Hirenachhaada** [comment]
it's nice, but the main issue was with the alignment or say, position. This means when you click on the message which is on the right side then the dropdown should appear in the right side, similarly the message on left side should bring the dropdown for copy and delete on the left side of the screen.

**Comment by SimonShangpliang** [comment]
I am working on it , will be done by 10/12/2023 EOD

**Comment by Hirenachhaada** [comment]
ok

**Comment by SimonShangpliang** [comment]
![left 1](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/118509034/e14a1222-a0ac-47cc-acfb-e7167b1645dd)
![left 2](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/118509034/326a2aac-3a2b-4ac5-8b1e-a715d0275f33)
![right width](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/118509034/ae28ee37-236f-4e20-ab98-91a2704f16d4)

**Comment by SimonShangpliang** [comment]
@Hirenachhaada

**Comment by Hirenachhaada** [comment]
Looking nice. You can create the pull request
