### ISSUE TITLE
Fix the size of message container of different attachments

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#4]
For different attachments the size of message container should dynamically change. you can see the bug in the attached image the extra space after the main image is of no use.
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/95188259/fec4317e-4e64-4955-b054-cd5798c4d814)

Similarly fix it  for all the types of attachments

**Comment by Surajit0573** [comment]
I can fix this issue, please assign me !!!

**Comment by Hirenachhaada** [comment]
First work on this issue. Then you can move to next issue

**Comment by Albert-2** [comment]
hey @Hirenachhaada
can you please assign me the issue as I am quite good at responsive designs and frontend 
THANK YOU FOR CONSIDERING...... :)

**Comment by Hirenachhaada** [comment]
Ok start working on it

**Comment by Albert-2** [comment]
ok..... 👍

**Comment by Albert-2** [comment]
hey @Hirenachhaada 
I set up the project but wont able to chat to see the actual issue can you please help me...??!!
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/90373859/df4f2bed-97b5-498a-b4c0-f64eb971e65c)
Thank you....!

**Comment by Albert-2** [comment]
hey @Hirenachhaada 
i've made a PR please review it 
If anything wrong or not as expected then please let me know
Thank You....

**Comment by Hirenachhaada** [comment]
ok nice your feature is working for different images but not for all type of attachments like video or audio and many more. Try to fix it 
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/95188259/fbe74f3d-db7e-4a44-99ef-d785a62b91b3)
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/95188259/f81def5b-045c-45cd-b891-3ea8124cc68a)

**Comment by Albert-2** [comment]
hey @Hirenachhaada
done what you asked
Still missed something then please do let me know...... ✌️

**Comment by Hirenachhaada** [comment]
Have you fixed it for all types of attachments?

**Comment by Hirenachhaada** [comment]
Just share a screenshot

**Comment by Albert-2** [comment]
![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/90373859/feaef6c5-d186-4e1b-b30f-708f23f9db3c)

here ....

**Comment by Hirenachhaada** [comment]
Ok nice, i am busy at some work. Will review and merge your code at night. 
By the way nice work 😀😀

**Comment by Hirenachhaada** [comment]
And one more thing , have you used any split function or any thing like that, because when i was trying to run it in my local environment, i was getting error related to it. Please check once

**Comment by Albert-2** [comment]
i also suffered from that "split function not applicable to undefined" problem but i fixed it 
and on my side its working like a charm

![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/90373859/12b1448e-1be3-4853-a3e9-95dd4f09665b)

![image](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/90373859/746c8328-fa61-40a7-a693-c2b9eb7bb610)

**Comment by Albert-2** [comment]
https://github.com/Hirenachhaada/Mern-Chat-Application/pull/29

check this branch its completely working as expected
