### ISSUE TITLE
Allow user to enter Multiline message

### ISSUE THREAD

**Issue by Hirenachhaada** [Hirenachhaada/Mern-Chat-Application#7]
Right now, users can only type messages on one line. Let's enable them to write messages using multiple lines.

**Comment by Hirenachhaada** [comment]
yes

**Comment by Hirenachhaada** [comment]
What's the status @involk-secure-1609 ??

**Comment by involk-secure-1609** [comment]
I am still doing it,will arrive at a solution by today

**Comment by involk-secure-1609** [comment]
I think i was able to provide a implementation of this feature,now if we hold shift and press enter we will be able to go to a new line and if we press enter it will directly send. 
It looks like this now 
![Screenshot from 2023-12-11 02-46-54](https://github.com/Hirenachhaada/Mern-Chat-Application/assets/133996079/b8ae93a8-3431-4d71-87fe-19edbf1c6023)

**Comment by Hirenachhaada** [comment]
You can create the pull request
